/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import adminui.AdminMainScreen;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDao;
import model.to.LoginInfoTo;
import userui.UserMainScreen;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/planeicon.png"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {
        }
        setSize(700, 450);
        setLocationRelativeTo(null);
        //jLabel2.setForeground(Color.white);
        //jLabel3.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jtfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Frame");
        setBackground(java.awt.Color.yellow);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("deskpane"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 200, 223, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Username :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 223, 44);

        jtfUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUsername);
        jtfUsername.setBounds(310, 110, 318, 46);

        jtfPassword.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(jtfPassword);
        jtfPassword.setBounds(310, 200, 318, 44);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(200, 290, 327, 57);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/bg_image.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String uname = jtfUsername.getText().trim();
        String upass = new String(jtfPassword.getPassword());
        String message = "";
        if (Validations.isEmpty(uname) || Validations.isEmpty(upass)) {
            message = "Please Fill All Boxes";
        } else {
            LoginInfoDao action = new LoginInfoDao();
            LoginInfoTo record = action.getRecord(uname);
            if (record != null) {
                if (record.getPassword().equals(upass)) {
                    if (record.getRolename().equals("admin") || record.getRolename().equals("Admin") || record.getRolename().equals("ADMIN")) {
                        AdminMainScreen am = new AdminMainScreen();
                        am.setVisible(true);
                        if (record.getLastlogin() == null) {
                            am.setTitle("Welcome First Time");
                        } else {
                            am.setTitle(" Your Last Visit : " + record.getLastlogin());
                        }
                        record.setLastlogin(new Timestamp(new java.util.Date().getTime()));
                        action.updateRecord(record);
                        message += " WELCOME ADMIN";
                        dispose();
                    } else if (record.getRolename().equals("user") || record.getRolename().equals("User") || record.getRolename().equals("USER")) {
                        UserMainScreen us = new UserMainScreen();
                        us.setVisible(true);
                        message += " Welcome" + uname;
                        if (record.getLastlogin() == null) {
                            us.setTitle("Welcome "+ uname+" For First Time ");
                        }else{
                            us.setTitle("Your Last Visit is : "+record.getLastlogin());
                        }
                        record.setLastlogin(new Timestamp(new java.util.Date().getTime()));
                        action.updateRecord(record);
                        dispose();
                    } else {
                        message += " Cannot Login In Due To Unauthorisation! ";
                    }
                } else {
                    message += " Invalid User Name And Password ";
                }
            } else {
                message += "  User Name And Password Given is Invalid";
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
