/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.AirlineInfoDao;
import model.to.AirlineInfoTo;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class AddAirlineInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddAirlineInfo
     */
    public AddAirlineInfo() {
        initComponents();
        getRootPane().setDefaultButton(btnAirlineInfo);
        setSize(650, 450);
    }

    public AddAirlineInfo(AirlineInfoTo record) {
        this();
        if (record != null) {
            jtfAirlineid.setText(record.getAirlineid());
            jtfAirlineName.setText(record.getAirlinename());
            setTitle("Edit Records in Databse");
            btnAirlineInfo.setText("Update Edited Records");
            jtfAirlineid.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtfAirlineName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfAirlineid = new javax.swing.JTextField();
        btnAirlineInfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Add Airline Info");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(500, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("EnterAirline Id :");

        jtfAirlineName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfAirlineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAirlineNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Airline Name :");

        jtfAirlineid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfAirlineid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAirlineidActionPerformed(evt);
            }
        });

        btnAirlineInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAirlineInfo.setText("Add Airline Info");
        btnAirlineInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jtfAirlineid, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnAirlineInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAirlineid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnAirlineInfo)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAirlineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAirlineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAirlineNameActionPerformed

    private void jtfAirlineidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAirlineidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAirlineidActionPerformed

    private void btnAirlineInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineInfoActionPerformed
        String airlineid = jtfAirlineid.getText().trim();
        String airlinename = jtfAirlineName.getText().trim();
        String message = "";
        if (Validations.isEmpty(airlineid) || Validations.isEmpty(airlinename)) {
            message = " Please Fill All the necessary Details!! ";
        } else {
            AirlineInfoTo record = new AirlineInfoTo();
            record.setAirlineid(airlineid);
            record.setAirlinename(airlinename);
            AirlineInfoDao action = new AirlineInfoDao();
            if (btnAirlineInfo.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = " Airline Details are saved.Thanku!! ";
                    JInternalFrame allframes[] = getDesktopPane().getAllFrames();
                        if(allframes!=null){
                            for(JInternalFrame jif : allframes){
                                if(jif instanceof ViewAirlineInfo){
                                    ((ViewAirlineInfo)jif).bindTableDetails();
                                    break;
                                }
                            }
                        }
                } else {
                    message = " Insertion does not proceed!!" + action.getErrormessage();
                }
            } else if (btnAirlineInfo.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = "Airline Details are Updated in Database";
                } else {
                    message = " Updation Failure : " + action.getErrormessage();
                }
                AllCommonOperations.openInternalFrames(getDesktopPane(), new ViewAirlineInfo());
                dispose();
            }
        }

        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAirlineInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirlineInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfAirlineName;
    private javax.swing.JTextField jtfAirlineid;
    // End of variables declaration//GEN-END:variables
}
