/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.BookingDetailsDao;
import model.dao.BookingInfoDao;
import model.dao.ClassCategoryDao;
import model.dao.CommonDao;
import model.to.BookingDetailsTo;
import model.to.BookingInfoTo;
import model.to.ClassCategoryTo;
import model.to.FlightInfoTo;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class AddBookingDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBookingDetails
     */
    private int did;

    public AddBookingDetails() {
        initComponents();
        getRootPane().setDefaultButton(btnBookingDetails);
        jcbbookingid.removeAllItems();
        jcbbookingid.addItem("Select Any Booking Id");
        List<BookingInfoTo> ids = new BookingInfoDao().getAllRecord();
        if (ids != null && ids.size() > 0) {
            for (BookingInfoTo id : ids) {
                jcbbookingid.addItem(id);
            }
        }
        jcbCategoryid.removeAllItems();
        jcbCategoryid.addItem("Select Any Class Category Id");
        List<ClassCategoryTo> categories = new ClassCategoryDao().getAllRecord();
        if (categories != null && categories.size() > 0) {
            for (ClassCategoryTo category : categories) {
                jcbCategoryid.addItem(category);
            }
        }

    }

    /*public AddBookingDetails(int did) {
        this();
        BookingDetailsTo record = new BookingDetailsDao().getRecord(did);
        if (record != null) {
            this.did = did;
            jcbbookingid.setSelectedItem(record.getBookingid());
            jcbCategoryid.setSelectedItem(record.getCategoryid());
            jtfPrice.setText(String.valueOf(record.getPrice()));
            jtfName.setText(record.getPassengername());
            jtfAge.setText(String.valueOf(record.getAge()));
            setTitle("Edit Booking Details");
            btnBookingDetails.setText("Update Student Details");
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jcbbookingid = new javax.swing.JComboBox();
        jcbCategoryid = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfAge = new javax.swing.JTextField();
        btnBookingDetails = new javax.swing.JButton();
        jtfName = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Booking Details");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Select Category Id:");

        jcbbookingid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbookingid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbookingidActionPerformed(evt);
            }
        });

        jcbCategoryid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCategoryid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoryidActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Enter Price :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Enter Passsenger's Name:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Enter Age :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Select Booking Id:");

        jtfAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAgeKeyTyped(evt);
            }
        });

        btnBookingDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBookingDetails.setText("Add Booking Details");
        btnBookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingDetailsActionPerformed(evt);
            }
        });

        jtfName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtfPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jcbCategoryid, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcbbookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbbookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCategoryid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnBookingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbbookingidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbookingidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbookingidActionPerformed

    private void jcbCategoryidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoryidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoryidActionPerformed

    private void btnBookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingDetailsActionPerformed
        String message = "";
        boolean allvalid = true;
        String price = jtfPrice.getText().trim();
        String name = jtfName.getText().trim();
        String age = jtfAge.getText().trim();
        if (jcbbookingid.getSelectedIndex() == 0) {
            message += "\n\n Please Select the Booking Id ";
            allvalid = false;
        }
        if (jcbCategoryid.getSelectedIndex() == 0) {
            message += "\n\n  Please Select the Class Category";
            allvalid = false;
        }
        if (Validations.isEmpty(name)) {
            allvalid = false;
            message += "\n\n Please Enter the Passenger's Name";
        }
        if (Validations.isEmpty(age)) {
            allvalid = false;
            message += "\n\n Please Enter the Passenger's Age";
        } else if (!Validations.isNumeric(age)) {
            message += "\n\nPlease Enter Numeric Value as Age Of Passenger";
            allvalid = false;
        } else {
            int a = Integer.parseInt(age);
            if (a <= 0 || a >= 90) {
                message += "\n\nPlease Enter Valid Age Of Passenger";
                allvalid = false;
            }
        }
        if (Validations.isEmpty(price)) {
            allvalid = false;
            message += "\n\n Please Enter the Price";
        } else if (Validations.isFloat(price)) {
            float p = Float.parseFloat(price);
            if (p <= 0) {
                message += "\n\nPlease Enter Valid Price";
                allvalid = false;
            }
        } else {
            message += "\n\nPlease Enter Numeric Value in Price Field";
            allvalid = false;
        }
        if (allvalid) {
            BookingDetailsTo record = new BookingDetailsTo();
            BookingInfoTo bt = (BookingInfoTo) jcbbookingid.getSelectedItem();
            record.setBookingid(bt.getBookingid());
            ClassCategoryTo cc = (ClassCategoryTo) jcbCategoryid.getSelectedItem();
            record.setCategoryid(cc.getCategoryid());
            record.setPassengername(name);
            record.setPrice(Float.parseFloat(price));
            record.setAge(Integer.parseInt(age));
            BookingDetailsDao action = new BookingDetailsDao();
            if (btnBookingDetails.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = "\n Booking Details are saved.Thanku!! ";
                    jcbCategoryid.setSelectedIndex(0);
                    jcbbookingid.setSelectedIndex(0);
                } else {
                    allvalid = false;
                    message = "\n Failure occur cann't insert Booking Details " + action.getErrormessage();
                }
            }else if (btnBookingDetails.getText().contains("Update")) {
                record.setDid(did);
                if (action.updateRecord(record)) {
                    message = "Booking Details are Updated in System";
                } else {
                    message = "Updation Failure :" + action.getErrormessage();
                    allvalid = false;
                }
                //AllCommonOperations.openInternalFrames(getDesktopPane(), new ViewBookingDetails());
                dispose();
            }
        }
        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBookingDetailsActionPerformed

    private void jtfAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAgeKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAgeKeyTyped

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingDetails;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jcbCategoryid;
    private javax.swing.JComboBox jcbbookingid;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPrice;
    // End of variables declaration//GEN-END:variables
}
