/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JOptionPane;
import model.dao.CountryInfoDao;
import model.to.CountryInfoTo;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class AddCountryDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCountryDetails
     */
    public AddCountryDetails() {
        initComponents();
        getRootPane().setDefaultButton(btnAddCountryDetails);
    }

    public AddCountryDetails(CountryInfoTo record) {
        this();
        if (record != null) {
            jtfCountryId.setText(record.getCountryid());
            jtfCountryName.setText(record.getCountryname());
            setTitle("Edit Records in Databse");
            btnAddCountryDetails.setText("Update Edited Records");
            jtfCountryId.setEditable(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCountryName = new javax.swing.JTextField();
        jtfCountryId = new javax.swing.JTextField();
        btnAddCountryDetails = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Country Details");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter Country Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Country Id :");

        jtfCountryName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtfCountryId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btnAddCountryDetails.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAddCountryDetails.setText("Add Country Details");
        btnAddCountryDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCountryDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCountryId, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(jtfCountryName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnAddCountryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCountryId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnAddCountryDetails)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCountryDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCountryDetailsActionPerformed
        String countryname = jtfCountryName.getText().trim();
        String countryid = jtfCountryId.getText().trim();
        String message = "";
        if (Validations.isEmpty(countryname) || Validations.isEmpty(countryid)) {
            message = " Please Fill All the necessary Details!! ";
        } else {
            CountryInfoTo record = new CountryInfoTo();
            record.setCountryname(countryname);
            record.setCountryid(countryid);
            CountryInfoDao action = new CountryInfoDao();
            if (btnAddCountryDetails.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = " Country Details are Saved. Thanku!! ";
                } else {
                    message = " Insertion does not proceed!!" + action.getErrormessage();
                }
            } else if (btnAddCountryDetails.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = " Country Details are Updated. Thanku!! ";
                } else {
                    message = " Updation does not proceed!!" + action.getErrormessage();
                }
                AllCommonOperations.openInternalFrames(getDesktopPane(), new ViewCountryInfo());
                dispose();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddCountryDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCountryDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfCountryId;
    private javax.swing.JTextField jtfCountryName;
    // End of variables declaration//GEN-END:variables
}
