/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JOptionPane;
import model.dao.ClassCategoryDao;
import model.to.ClassCategoryTo;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class AddClassCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddClassCategory
     */
    public AddClassCategory() {
        initComponents();
        getRootPane().setDefaultButton(btnClassCategoryDetails);
    }

    public AddClassCategory(ClassCategoryTo record) {
        this();
        if (record != null) {
            jtfCategoryId.setText(record.getCategoryid());
            jtfCategoryName.setText(record.getCategoryname());
            setTitle("Edit Records in Databse");
            btnClassCategoryDetails.setText("Update Edited Records");
            jtfCategoryId.setEditable(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtfCategoryName = new javax.swing.JTextField();
        btnClassCategoryDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfCategoryId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Passenger's Class Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Class Category Name :");

        jtfCategoryName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCategoryNameActionPerformed(evt);
            }
        });

        btnClassCategoryDetails.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnClassCategoryDetails.setText("Add Class Category");
        btnClassCategoryDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassCategoryDetailsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Class Category Id :");

        jtfCategoryId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfCategoryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCategoryIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jtfCategoryId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnClassCategoryDetails)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnClassCategoryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCategoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCategoryNameActionPerformed

    private void btnClassCategoryDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassCategoryDetailsActionPerformed
        String categoryid = jtfCategoryId.getText().trim();
        String categoryname = jtfCategoryName.getText().trim();
        String message = "";
        boolean allvalid = true;
        if (Validations.isEmpty(categoryid)) {
            allvalid = false;
            message += "\n Please Enter the Category Id";
        }
        if (Validations.isEmpty(categoryname)) {
            allvalid = false;
            message += "\n Please Enter the Category Name";
        }
        if (allvalid) {
            ClassCategoryTo record = new ClassCategoryTo();
            record.setCategoryid(categoryid);
            record.setCategoryname(categoryname);
            ClassCategoryDao action = new ClassCategoryDao();
            if (btnClassCategoryDetails.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = "\n Category Details Are Saved!";
                } else {
                    message = "\n Insertion Failed " + action.getErrormessage();
                }
            } else if (btnClassCategoryDetails.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = " Category Details are Updated. Thanku!! ";
                } else {
                    message = " Updation does not proceed!!" + action.getErrormessage();
                }
                AllCommonOperations.openInternalFrames(getDesktopPane(), new ViewCategoryDetails());
                dispose();
            }
        }
        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error Occcured", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnClassCategoryDetailsActionPerformed

    private void jtfCategoryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCategoryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCategoryIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassCategoryDetails;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCategoryId;
    private javax.swing.JTextField jtfCategoryName;
    // End of variables declaration//GEN-END:variables
}
