/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.CityInfoDao;
import model.dao.CountryInfoDao;
import model.to.CityInfoTo;
import model.to.CountryInfoTo;
import utility.AllCommonOperations;
import utility.Validations;

/**
 *
 * @author Pavneet
 */
public class AddCityInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCityInfo
     */
    public AddCityInfo() {
        initComponents();
        setSize(650, 450);
        getRootPane().setDefaultButton(btnCityInfo);
        jcbCountryId.removeAllItems();
        jcbCountryId.addItem("Choose Country");
        List<CountryInfoTo> countries = new CountryInfoDao().getAllRecord();
        if (countries != null && countries.size() > 0) {
            for (CountryInfoTo cit : countries) {
                jcbCountryId.addItem(cit);
            }
        }

    }

    public AddCityInfo(CityInfoTo record) {
        this();
        if (record != null) {
            jtfCityId.setText(record.getCityid());
            jtfCityName.setText(record.getCityname());
            for (int i = 1; i < jcbCountryId.getItemCount(); i++) {
                CountryInfoTo ct = (CountryInfoTo) jcbCountryId.getItemAt(i);
                if(ct.getCountryid().equals(record.getCountryid())){
                    jcbCountryId.setSelectedIndex(i);
                }
            }
            setTitle("Edit Records in Database");
            btnCityInfo.setText("Update Records");
            jtfCityId.setEditable(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtfCityName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCityId = new javax.swing.JTextField();
        jcbCountryId = new javax.swing.JComboBox();
        btnCityInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add City Infomation");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter City Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(52, 117, 221, 46);

        jtfCityName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtfCityName);
        jtfCityName.setBounds(350, 123, 278, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Select Country Id :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(52, 189, 235, 61);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Enter City Id:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(52, 38, 208, 46);

        jtfCityId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtfCityId);
        jtfCityId.setBounds(350, 44, 278, 35);

        jcbCountryId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbCountryId);
        jcbCountryId.setBounds(350, 201, 278, 46);

        btnCityInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnCityInfo.setText("Add City Info");
        btnCityInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCityInfo);
        btnCityInfo.setBounds(175, 296, 319, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/backpic.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCityInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityInfoActionPerformed
        String message = "";
        boolean allvalid = true;
        String cityid = jtfCityId.getText().trim();
        String cityname = jtfCityName.getText().trim();
        if (jcbCountryId.getSelectedIndex() == 0) {
            message += "\n Please Select the County Id ";
            allvalid = false;
        }
        if (Validations.isEmpty(cityid)) {
            allvalid = false;
            message += "\n Please Enter the City Id ";
        }
        if (Validations.isEmpty(cityname)) {
            allvalid = false;
            message += "\n Please Enter the City Name ";
        }
        if (allvalid) {
            CityInfoTo record = new CityInfoTo();
            record.setCityid(cityid);
            record.setCityname(cityname);
            CountryInfoTo ct = (CountryInfoTo) jcbCountryId.getSelectedItem();
            record.setCountryid(ct.getCountryid());
            CityInfoDao action = new CityInfoDao();
            if (btnCityInfo.getText().contains("Add")) {
                if (action.insertRecord(record)) {
                    message = "\n City Details are Saved. ";
                } else {
                    allvalid = false;
                    message = "\n Failure occur cann't insert City Details ";
                }
            } else if (btnCityInfo.getText().contains("Update")) {
                if (action.updateRecord(record)) {
                    message = "City Details are Updated in Database";
                } else {
                    message = " Updation Failure:" + action.getErrormessage();
                }
                AllCommonOperations.openInternalFrames(getDesktopPane(), new ViewCityDetails());
                dispose();
            }

        }
        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCityInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCityInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcbCountryId;
    private javax.swing.JTextField jtfCityId;
    private javax.swing.JTextField jtfCityName;
    // End of variables declaration//GEN-END:variables
}
