/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.ImageIcon;
import static utility.AllCommonOperations.openInternalFrames;

/**
 *
 * @author Pavneet
 */
public class AdminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/planeicon.png"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {
        }
        setTitle("Welcome to Admin Section");
        initComponents();
        setSize(1050, 650);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemAddAilrine = new javax.swing.JMenuItem();
        jMenuItemViewAilrine = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAddCountry = new javax.swing.JMenuItem();
        jMenuItemViewCountry = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAddCity = new javax.swing.JMenuItem();
        jMenuItemViewCity = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItemAddCategory = new javax.swing.JMenuItem();
        jMenuItemViewCategory = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAddFlight = new javax.swing.JMenuItem();
        jMenuItemViewFlight = new javax.swing.JMenuItem();
        jMenuItemAddPrices = new javax.swing.JMenuItem();
        jMenuItemViewPrices = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAddBookings = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(deskpane, java.awt.BorderLayout.CENTER);

        jMenu7.setText("Airline Operations");

        jMenuItemAddAilrine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddAilrine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddAilrine.setText("Add Airline To be Booked");
        jMenuItemAddAilrine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddAilrineActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemAddAilrine);

        jMenuItemViewAilrine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewAilrine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewAilrine.setText("View  Airlines Available");
        jMenuItemViewAilrine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewAilrineActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemViewAilrine);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Country Operations");

        jMenuItemAddCountry.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddCountry.setText("Add Country Details");
        jMenuItemAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCountryActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemAddCountry);

        jMenuItemViewCountry.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewCountry.setText("View Country Details");
        jMenuItemViewCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewCountryActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemViewCountry);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("City Operations");

        jMenuItemAddCity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddCity.setText("Add City Details");
        jMenuItemAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCityActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAddCity);

        jMenuItemViewCity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewCity.setText("View City Details");
        jMenuItemViewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewCityActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemViewCity);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Class Category Operations");

        jMenuItemAddCategory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddCategory.setText("Add Passeneger's CLass Category");
        jMenuItemAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCategoryActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemAddCategory);

        jMenuItemViewCategory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewCategory.setText("View Passenger's Class Category");
        jMenuItemViewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewCategoryActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemViewCategory);

        jMenuBar1.add(jMenu8);
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Flight Operation");

        jMenuItemAddFlight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddFlight.setText("Add New Flight");
        jMenuItemAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFlightActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddFlight);

        jMenuItemViewFlight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewFlight.setText("View Flight Details");
        jMenuItemViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewFlightActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemViewFlight);

        jMenuItemAddPrices.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddPrices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddPrices.setText("Add  Flight Prices");
        jMenuItemAddPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddPricesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddPrices);

        jMenuItemViewPrices.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemViewPrices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/view.png"))); // NOI18N
        jMenuItemViewPrices.setText("View Flight Prices");
        jMenuItemViewPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewPricesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemViewPrices);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Booking Operations");

        jMenuItemAddBookings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItemAddBookings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItemAddBookings.setText("Add Flight Bookings");
        jMenuItemAddBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddBookingsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAddBookings);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu4);

        jMenu9.setText("Sign Up Operation");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/add.png"))); // NOI18N
        jMenuItem1.setText("Add User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemViewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCityActionPerformed
        openInternalFrames(deskpane, new ViewCityDetails());
    }//GEN-LAST:event_jMenuItemViewCityActionPerformed

    private void jMenuItemAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCityActionPerformed
        openInternalFrames(deskpane, new AddCityInfo());
    }//GEN-LAST:event_jMenuItemAddCityActionPerformed

    private void jMenuItemViewPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewPricesActionPerformed
        openInternalFrames(deskpane, new ViewPriceDetails());
    }//GEN-LAST:event_jMenuItemViewPricesActionPerformed

    private void jMenuItemAddPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddPricesActionPerformed
        openInternalFrames(deskpane, new AddFlightPrice());
    }//GEN-LAST:event_jMenuItemAddPricesActionPerformed

    private void jMenuItemViewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCategoryActionPerformed
        openInternalFrames(deskpane, new ViewCategoryDetails());
    }//GEN-LAST:event_jMenuItemViewCategoryActionPerformed

    private void jMenuItemAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCategoryActionPerformed
        openInternalFrames(deskpane, new AddClassCategory());
    }//GEN-LAST:event_jMenuItemAddCategoryActionPerformed

    private void jMenuItemViewAilrineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewAilrineActionPerformed
        openInternalFrames(deskpane, new ViewAirlineInfo());
    }//GEN-LAST:event_jMenuItemViewAilrineActionPerformed

    private void jMenuItemAddAilrineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAilrineActionPerformed
        openInternalFrames(deskpane, new AddAirlineInfo());
    }//GEN-LAST:event_jMenuItemAddAilrineActionPerformed

    private void jMenuItemAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCountryActionPerformed
        openInternalFrames(deskpane, new AddCountryDetails());
    }//GEN-LAST:event_jMenuItemAddCountryActionPerformed

    private void jMenuItemAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFlightActionPerformed
        openInternalFrames(deskpane, new AddFlightDetails());
    }//GEN-LAST:event_jMenuItemAddFlightActionPerformed

    private void jMenuItemViewCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCountryActionPerformed
        openInternalFrames(deskpane, new ViewCountryInfo());
    }//GEN-LAST:event_jMenuItemViewCountryActionPerformed

    private void jMenuItemViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewFlightActionPerformed
        openInternalFrames(deskpane, new ViewFlightInfo());
    }//GEN-LAST:event_jMenuItemViewFlightActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openInternalFrames(deskpane, new AdminSignUpFrame());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemAddBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddBookingsActionPerformed
        openInternalFrames(deskpane, new BookingOperations());
    }//GEN-LAST:event_jMenuItemAddBookingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminMainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskpane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAddAilrine;
    private javax.swing.JMenuItem jMenuItemAddBookings;
    private javax.swing.JMenuItem jMenuItemAddCategory;
    private javax.swing.JMenuItem jMenuItemAddCity;
    private javax.swing.JMenuItem jMenuItemAddCountry;
    private javax.swing.JMenuItem jMenuItemAddFlight;
    private javax.swing.JMenuItem jMenuItemAddPrices;
    private javax.swing.JMenuItem jMenuItemViewAilrine;
    private javax.swing.JMenuItem jMenuItemViewCategory;
    private javax.swing.JMenuItem jMenuItemViewCity;
    private javax.swing.JMenuItem jMenuItemViewCountry;
    private javax.swing.JMenuItem jMenuItemViewFlight;
    private javax.swing.JMenuItem jMenuItemViewPrices;
    // End of variables declaration//GEN-END:variables
}
