/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.FlightInfoDao;
import model.to.FlightInfoTo;
import utility.AllCommonOperations;

/**
 *
 * @author Pavneet
 */
public class ViewFlightInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewFlightInfo
     */
    private List<FlightInfoTo> alldetails;
    private int flightid;
    private int srow;
    private JPopupMenu popup;
    public ViewFlightInfo() {
        initComponents();
        //setLocation(200,400);
        flightid = 0;
        bindTableDetails();
        tableflightdetails.setRowHeight(25);
        tableflightdetails.setShowGrid(true);
        tableflightdetails.setBackground(new Color(0,150,200));
        tableflightdetails.setForeground(Color.WHITE);
        tableflightdetails.setSelectionBackground(Color.white);
        tableflightdetails.setSelectionForeground(new Color(0,150,200));
       
        popup = new JPopupMenu();
        JMenuItem deleterecord = new JMenuItem(" Delete Record");
        deleterecord.setFont(new Font("Times New Roman", Font.BOLD, 25));
        JMenuItem editrecord = new JMenuItem(" Edit Record");
        editrecord.setFont(new Font("Times New Roman", Font.BOLD, 25));
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/adminui/delete1.png"));
            deleterecord.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/adminui/add.png"));
            editrecord.setIcon(icon);
        } catch (Exception ex) {
        }
        popup.add(deleterecord);
        popup.add(editrecord);
        deleterecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });

        editrecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }

    private void deleteRecord() {
        if (flightid != 0) {
            int result = JOptionPane.showConfirmDialog(this, "Do You Really Want to Delete this record ?", "Message From System", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                FlightInfoTo ct = alldetails.get(srow);
                FlightInfoDao action = new FlightInfoDao();
                String message = "";
                if (action.deleteRecord(ct.getFlightid())) {
                    message = " Your Desired Record is Deleted. ";
                    bindTableDetails();
                } else {
                    message = " Sorry, Cann't Delete this Record " + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        flightid = 0;
    }

    private void editRecord() {
        if (flightid != 0) {
            AllCommonOperations.openInternalFrames(getDesktopPane(), new AddFlightDetails(flightid));
            dispose();

        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableflightdetails = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Flight Details");

        tableflightdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableflightdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableflightdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableflightdetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableflightdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableflightdetailsMouseClicked
        if(evt.getButton()== MouseEvent.BUTTON3)
        {
            int point=tableflightdetails.rowAtPoint(evt.getPoint());
            tableflightdetails.getSelectionModel().setSelectionInterval(point, point);
            srow =tableflightdetails.getSelectedRow();
            flightid=Integer.parseInt(tableflightdetails.getValueAt(srow, 0).toString());
            popup.show(tableflightdetails, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableflightdetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableflightdetails;
    // End of variables declaration//GEN-END:variables

    public void bindTableDetails() {
        alldetails = new FlightInfoDao().getAllRecord();
        String[] col_names = {" Flight Id ", " Airline Name ","Country Name", " SourceCity Name", "DestinationCity Name", "Flight Type", "Departure Time", "Journey Minutes"};
        Object[][] records = null;
        if (alldetails != null && alldetails.size() > 0) {
            records = new Object[alldetails.size()][col_names.length];
            int i = 0;
            for (FlightInfoTo ft : alldetails) {
                records[i] = new Object[]{ft.getFlightid(), ft.getAirlinename(),ft.getCountryname()+"["+ ft.getCountryid()+"]", ft.getSourcecityname(), ft.getDestinationcityname(), ft.getFlighttype(), ft.getDeparturetime(), ft.getJourneyminute()};
                i++;
            }
        } else {
            records = new Object[1][col_names.length];
            records[0] = new Object[]{"No Records", "No Records"," No Records", " No Records", "No Records", "No Records", "No Records", "No Records"};
        }
        

        DefaultTableModel dtm = new DefaultTableModel(records, col_names) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableflightdetails.getTableHeader().setReorderingAllowed(false);
        tableflightdetails.setModel(dtm);
    }
}
