/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.ClassCategoryDao;
import model.to.ClassCategoryTo;
import utility.AllCommonOperations;

/**
 *
 * @author Pavneet
 */
public class ViewCategoryDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCategoryDetails
     */
    private List<ClassCategoryTo> alldetails;
    private int srow;
    private JPopupMenu popup;

    public ViewCategoryDetails() {
        initComponents();
        bindTableDetails();
        tableCategoryDetails.setRowHeight(25);
        tableCategoryDetails.setShowGrid(true);
        tableCategoryDetails.setBackground(new Color(0,150,200));
        tableCategoryDetails.setForeground(Color.WHITE);
        tableCategoryDetails.setSelectionBackground(Color.white);
        tableCategoryDetails.setSelectionForeground(new Color(0,150,200));
        srow = -1;
        popup = new JPopupMenu();
        JMenuItem deleterecord = new JMenuItem(" Delete Record");
        deleterecord.setFont(new Font("Times New Roman", Font.BOLD, 25));
        JMenuItem editrecord = new JMenuItem(" Edit Record");
        editrecord.setFont(new Font("Times New Roman", Font.BOLD, 25));
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/adminui/delete1.png"));
            deleterecord.setIcon(icon);
        } catch (Exception ex) {
        }
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/adminui/add.png"));
            editrecord.setIcon(icon);
        } catch (Exception ex) {
        }
        popup.add(deleterecord);
        popup.add(editrecord);
        deleterecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });

        editrecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }

    private void deleteRecord() {
        if (srow != -1 && alldetails != null && srow < alldetails.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Do You Really Want to Delete this record ?", "Message From System", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                ClassCategoryTo ct = alldetails.get(srow);
                ClassCategoryDao action = new ClassCategoryDao();
                String message = "";
                if (action.deleteRecord(ct.getCategoryid())) {
                    message = " Your Desired Record is Deleted. ";
                    bindTableDetails();
                } else {
                    message = " Sorry, Cann't Delete this Record " + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow = -1;
    }

    private void editRecord() {
        if (srow != -1 && alldetails != null && srow < alldetails.size()) {
            AllCommonOperations.openInternalFrames(getDesktopPane(),new AddClassCategory(alldetails.get(srow)));
            dispose();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategoryDetails = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Class Category Details");

        tableCategoryDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategoryDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategoryDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCategoryDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryDetailsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int point = tableCategoryDetails.rowAtPoint(evt.getPoint());
            tableCategoryDetails.getSelectionModel().setSelectionInterval(point, point);
            srow = tableCategoryDetails.getSelectedRow();
            popup.show(tableCategoryDetails, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableCategoryDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCategoryDetails;
    // End of variables declaration//GEN-END:variables

    private void bindTableDetails() {
        alldetails = new ClassCategoryDao().getAllRecord();
        String[] col_names = {" Category Id ", " Category Name "};
        Object[][] records = null;
        if (alldetails != null && alldetails.size() > 0) {
            records = new Object[alldetails.size()][col_names.length];
            int i = 0;
            for (ClassCategoryTo ct : alldetails) {
                records[i] = new Object[]{ct.getCategoryid(), ct.getCategoryname()};
                i++;
            }
        } else {
            records = new Object[1][col_names.length];
            records[0] = new Object[]{"No Records", "No Records"};
        }

        DefaultTableModel dtm = new DefaultTableModel(records, col_names) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableCategoryDetails.getTableHeader().setReorderingAllowed(false);
        tableCategoryDetails.setModel(dtm);
    }
}
